// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQBdrMP_l7tKp-Q4RLtdy7AFaP2km9r4',
    appId: '1:467322917635:web:75dd78140b930e67838f36',
    messagingSenderId: '467322917635',
    projectId: 'vezeeta-a2089',
    authDomain: 'vezeeta-a2089.firebaseapp.com',
    storageBucket: 'vezeeta-a2089.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwundD3meiu9zq96Bl5ll-Dyln5WItQC8',
    appId: '1:467322917635:android:61d4519a2090d7ad838f36',
    messagingSenderId: '467322917635',
    projectId: 'vezeeta-a2089',
    storageBucket: 'vezeeta-a2089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0LiOYB54cxHoCiweTOMZ7rkadB0GI_Y',
    appId: '1:467322917635:ios:7d4b4b6893f0fa2c838f36',
    messagingSenderId: '467322917635',
    projectId: 'vezeeta-a2089',
    storageBucket: 'vezeeta-a2089.appspot.com',
    iosClientId: '467322917635-49u033lsmlu4vihltfmkr788ij63m7p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vezeetaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM0LiOYB54cxHoCiweTOMZ7rkadB0GI_Y',
    appId: '1:467322917635:ios:7d4b4b6893f0fa2c838f36',
    messagingSenderId: '467322917635',
    projectId: 'vezeeta-a2089',
    storageBucket: 'vezeeta-a2089.appspot.com',
    iosClientId: '467322917635-49u033lsmlu4vihltfmkr788ij63m7p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vezeetaApp',
  );
}
